services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/data:/app/backend/data
    environment:
      - PYTHONUNBUFFERED=1
    init: true

volumes:
  backend_data: 